- name: Install wget & Unzip package
  yum: name={{ item }} state=latest
  with_items:
    - wget
    - unzip

- name: Download Java from ORACLE JDK site
  command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"

- name: Unpack archive Oracle JDK
  command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"

- name: Fix ownership Oracle JDK
  file: state=directory path={{java_name}} owner=root group=root recurse=yes

- name: Make Java available for the system
  command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

- name: Clean up
  file: state=absent path={{java_archive}}
